version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  mvcwebapp:
    image: mvcwebapp:dev
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: MvcWebApp/Dockerfile
    ports:
      - "5000:80"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    container_name: postgredbs
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "notedb"
    networks:
      - dockerapi-dev

volumes:
  db_volume:

